from AoC_tools import aoc22 as aoc

data = aoc.read_input("testinput2.txt")
data = list(map(list, data))

grid = aoc.Grid.read(data)
grid.display()
# grid.transpose()
# grid.display()
# grid.flip_v()
# grid.display()
# grid.flip_h()
# grid.display()
# grid.transpose()
# grid.display()
p = aoc.Point(2,2)
print(p)
print(f"Point value: {grid.values[p.pos]}")
N = grid.get_north(p)
print(f"north: {N.pos},{grid.values[N.pos]}")
E = grid.get_east(p)
print(f"east: {E.pos},{grid.values[E.pos]}")
S = grid.get_south(p)
print(f"south: {S.pos},{grid.values[S.pos]}")
W = grid.get_west(p)
print(f"west: {W.pos},{grid.values[W.pos]}")

NE = grid.get_northeast(p)
print(f"northeast: {NE.pos},{grid.values[NE.pos]}")
SE = grid.get_southeast(p)
print(f"southeast: {SE.pos},{grid.values[SE.pos]}")
SW = grid.get_southwest(p)
print(f"southwest: {SW.pos},{grid.values[SW.pos]}")
NW = grid.get_northwest(p)
print(f"northwest: {NW.pos},{grid.values[NW.pos]}")
